### ISSUE TITLE
Mac Safari

### ISSUE THREAD

**Issue by aModernGirlMakes** [jneilliii/OctoPrint-M300Player#3]
I see that this was tested in Chrome. I installed it and checked in Chrome on a Mac but did not have success. 

How can I run a test? I am not sure I know the expected behavior. I was thinking this would be a good solution to losing the speaker on my Ender 3 Pro after installing a BL Touch. 

It could be that I don't understand the intended use for the plug in. 

Thanks for your help.

**Comment by jneilliii** [comment]
So the plugin will interpret the [M300 gcode](https://reprap.org/wiki/G-code#M300:_Play_beep_sound) as it's sent to the printer and play it in a browser. Once installed when you send an M300 command from the terminal tab or if it's embedded in your gcode stored local in octoprint it will make a beep noise. For example sending this. You can adjust how the sound is generated in the plugin's settings.

```
M300 S300 P1000
```

**Comment by jneilliii** [comment]
And you check the compatibility of your browser here.

https://developer.mozilla.org/en-US/docs/Web/API/AudioContext#Browser_compatibility
