### ISSUE TITLE
M300Player does not play a tone for me

### ISSUE THREAD

**Issue by alsmithson** [jneilliii/OctoPrint-M300Player#7]
Using Chrome or Safari (both on a Mac), I never get a sound (I've been trying to use M300Player for several months). I have an Artillery Sidewinder X1 which uses a TFT controller, and the printer itself does not recognize the M300 command. But should that stop the M300Player plugin from working? I have tried it by putting M300 commands such as M300 S600 P200 in the gcode and I've tried typing it into the OctoPrint control panel. I get nothing either way.

Update: I connected my bluetooth headphones which automatically launched iTunes. I started listening to a song while I continued to fiddle with m300 commands in the control panel. At some point it started working in Safari, then in Chrome. Its a crapshoot if it works tomorrow...

**Comment by jneilliii** [comment]
No, the printer shouldn't matter. It should work with the browser window open unless there is some security setting preventing it from working. If you open your develoepr console in chrom (f12) and load the page then send the command via terminal do you see any errors on initial load of the page or are there any errors in your octoprint.log that may be relevant?
